version: '2'

services:
    lb:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - /vagrant/local/docker/lb/config/default.conf:/etc/nginx/conf.d/default.conf
