version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - /vagrant/local/docker/html/hello-world:/html
            - /vagrant/local/docker/config/site.conf:/etc/nginx/conf.d/default.conf
