
Vagrant.configure("2") do |config|
	config.vm.define :app_docker do |app_config|
  		app_config.vm.box = "puppetlabs/ubuntu-14.04-64-nocm"
  		app_config.vm.network "forwarded_port", guest: 80, host: 80
  		app_config.vm.provision "shell", path: "config/init.sh"
  		app_config.vm.hostname = "docker.al.local"
  		app_config.vm.synced_folder ".", "/vagrant", disabled: true
  		app_config.vm.synced_folder "guest/", "/vagrant/local"
  		app_config.vm.provision "puppet" do |puppet| 
			puppet.manifests_path = "guest/puppet/" 
			puppet.manifest_file = "init_local.pp"
		end
  	end
end
