version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - /vagrant/local/docker/html/random:/html
            - /vagrant/local/docker/app/config/site.conf:/etc/nginx/conf.d/default.conf
